version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch55-data:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
volumes:
  elasticsearch55-data:
    driver: local
